### ISSUE TITLE
Ошибки при обрезании строки description & ошибка сохранения дефолтного изображения

### ISSUE THREAD

**Issue by agpopov** [darkfriend/dev2fun.opengraph#1]
Модуль отличный, мне понравился. В процессе внедрения обнаружил несколько ошибок.

Первое - это потеря всего значения og:description  при определённом наборе символов. Легко решается использованием mb_* версиями функций. Ну, или как-то хитрее с кодировками возиться. Вот как у меня работает (OpenGraph.php: 964): 
```
if (mb_strlen($text) > 160) {
    $text = mb_substr($text, 0, 160) . '...';
}
```
Если интересно, ошибка вылезла при таком описании `Бланковая худи оверсайз фиолетового цвета с заниженным втачным рукавом, двумя потайными карманами и скрытой регулируемой резинкой внизу.`

А со вторым всё сложнее. Проблема сохранения дефолтного изображения появляется, когда папка хранения временных файлов вынесена за пределы корня сайта. Так рекомендует делать модуль проактивной защиты Битрикс. В итоге долгих изысканий я пришёл к вот такому решению (dev2fun_settings.php: 105):
```
if (!empty($_POST["DEFAULT_IMAGE"])) {
    $_POST['DEFAULT_IMAGE'] = CIBlock::makeFileArray($_POST['DEFAULT_IMAGE']);
    $fileID = \CFile::SaveFile($_POST['DEFAULT_IMAGE'], 'dev2fun_opengraph', true);
    if ($fileID) {
        Option::set(dev2funModuleOpenGraphClass::$module_id, 'DEFAULT_IMAGE', $fileID);
    }
}
```

Я был бы очень признателен, если бы Вы обновили модуль в маркетплейсе битрикса, чтобы в следующем проекте не пришлось руками править файлы моделя.

**Comment by darkfriend** [comment]
Здравствуйте!
Спасибо за ваш issue :)
Извиняюсь, что моя реакция оказалась на столько долгой 😢 
Очень правильные правки! 👍 

Добавил их в версию 1.4.1.
Вы также можете не стесняться делать Pull Request 😄

**Comment by darkfriend** [comment]
[1.4.1](https://github.com/darkfriend/dev2fun.opengraph/releases/tag/1.4.1)
